CREATE TABLE Modules(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PackageId NVARCHAR(210) NOT NULL,
	ActivatedVersion NVARCHAR(210) NOT NULL,
	Activated BIT NOT NULL DEFAULT(1),
	RawAssembly VARBINARY(MAX) NOT NULL
);